include classpath("application.conf")

akka.http.server.request-timeout = 30 seconds

queues {
    consumer {
        defaultVisibilityTimeout = 10 seconds
        delay = 0 seconds
        receiveMessageWait = 0 seconds
        deadLettersQueue {
            name = "consumer-dead"
            maxReceiveCount = 1
        }
        tags {
        }
    }
    producer {
        defaultVisibilityTimeout = 10 seconds
        delay = 0 seconds
        receiveMessageWait = 0 seconds
        deadLettersQueue {
            name = "producer-dead"
            maxReceiveCount = 1
        }
        tags {
        }
    }
    consumer-dead {
    }
    producer-dead {
    }

    "producer.fifo" {
        defaultVisibilityTimeout = 10 seconds
        delay = 0 seconds
        receiveMessageWait = 0 seconds
        fifo = true
        contentBasedDeduplication = false
        deadLettersQueue {
            name = "producer-fifo-dead.fifo"
            maxReceiveCount = 1
        }
        tags {
        }
    }
    "consumer.fifo" {
        defaultVisibilityTimeout = 10 seconds
        delay = 0 seconds
        receiveMessageWait = 0 seconds
        fifo = true
        contentBasedDeduplication = false
        deadLettersQueue {
            name = "consumer-fifo-dead.fifo"
            maxReceiveCount = 1
        }
        tags {
        }
    }
    "producer-fifo-dead.fifo" {
        fifo = true
    }
    "consumer-fifo-dead.fifo" {
        fifo = true
    }
}
